# Author: Ryan H.
# Filename: .zshenv
# Imports things needed for any and all shells.

##################
# $path settings #
##################
# This forces $path to only hold unique values.
typeset -U path

# Add our special stuff to $path then add everything already in $path.
path=(
    "$N_PREFIX/bin"
    "/opt/homebrew/bin"
    "/opt/homebrew/sbin"
    $path
)

# Import functions
source ~/.local/user/functions

# Homebrew cask installs no longer trigger MacOS Gatekeeper.
export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"

# Have 'n' install to ~/.n instead of /usr/local
export N_PREFIX="$HOME/.n"

# Set the DOTNET_ROOT in case software needs it.
export DOTNET_ROOT="$(brew --prefix)/opt/dotnet/libexec"

# Set 'bat's config location
export BAT_CONFIG_PATH="$HOME/.config/bat/bat.conf"
