# Author: Ryan H.
# Filename: .zshrc
# Holds a bunch of imports that hold the important stuff to help keep things modular/easy to update.

# Set variables
# Syntax highlighting for man pages via 'bat'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Homebrew cask installs no longer trigger MacOS Gatekeeper.
export HOMEBREW_CASK_OPTS="--no-quarantine"

# Changes <<< to use bat instead of cat (default).
export NULLCMD='bat'

# Change ZSH options

# Import aliases
source ~/.shell/aliases

# Customize prompt(s)
PROMPT='
%n on %m in %~
$ '

# Add locations to $PATH

# Import Oh My Zsh stuff
#source ~/.ohmyzsh

