# Author: Ryan H.
# Filename: .zshrc
# Holds a bunch of imports that hold the important stuff to help keep things modular/easy to update.

# Set variables
# Syntax highlighting for man pages via 'bat'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Change ZSH options

# Import aliases:
source ~/.aliases

# Customize prompt(s)
PROMPT='
%n on %m in %~
$ '

# Add locations to $PATH
export PATH="/opt/homebrew/bin:$PATH"


#
# Functions!
#

# Make a new directory(ies) and CD into it.
function mkcd() {
    mkdir -p "$@" && cd "$_";
}

# Import Oh My Zsh stuff:
#source ~/.ohmyzsh

